name: crypto_future_builder
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  http: ^1.2.2
  get_it: ^8.0.2
  intl: ^0.20.0
  json_annotation: ^4.9.0
  decorated_icon: ^1.2.1
  

dev_dependencies:
  test: ^1.25.7
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  platform: ^3.1.4
  file: ^7.0.0
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
